<?php

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */


function sf_create_metaboxes( $meta_boxes ) {
    $prefix = 'ap-';

    $meta_boxes[] = array(
        'id' => 'project-info',
        'title' => esc_html__( 'Project Info', 'understrap' ),
        'post_types' => array( 'project' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            array(
                'id' => $prefix . 'video',
                'type' => 'text',
                'name' => esc_html__( 'Video ID ', 'understrap' ),
                'description' => 'This is the unique id of the video usually in like this228414948. Only VIMEO supported',
                'std' => '229545027',
            ),
            array(
                'id' => $prefix . 'client',
                'type' => 'text',
                'name' => esc_html__( 'Client Name', 'understrap' ),
                'std' => 'Test Company GmbH',
            ),
            array(
                'id' => $prefix . 'area',
                'type' => 'text',
                'name' => esc_html__( 'Short Description', 'understrap' ),
                'std' => 'This is a short description for this movie',
            ),
            array(
                'id' => $prefix . 'additional image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Extra Image', 'understrap' ),
            ),
        ),
    );

    return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'sf_create_metaboxes' );